In [23]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [24]:
# 데이터 로드
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
# 제외 대상 컬럼 드랍 (PassengerId, Name, Ticket, Cabin)
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

# 결측치 처리 (결측된 데이터 생성)
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# 결측치 처리 (결측된 열 제거)
#

# 범주형 데이터 인코딩
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [7]:
# 데이터 분할
X = df.drop('Survived', axis=1)
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
# 데이터 정규화
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
# 1. DecisionTreeClassifier
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
print(f"Decision Tree Accuracy: {accuracy_score(y_test, dt_pred):.4f}")
# 실제 값 vs 예측 값 비교
comparison_df = pd.DataFrame({
    '실제 값': y_test[:15].values,
    '예측 값': dt_pred[:15]
})
print("\n--- 실제 값 vs 예측 값 비교 (DecisionTree) ---")
print(comparison_df)

Decision Tree Accuracy: 0.7765

--- 실제 값 vs 예측 값 비교 (DecisionTree) ---
    실제 값  예측 값
0      1     0
1      0     0
2      0     0
3      1     1
4      1     1
5      1     0
6      1     1
7      0     0
8      1     1
9      1     1
10     0     0
11     0     0
12     0     0
13     0     0
14     0     0

In [16]:
# 2. RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
print(f"Random Forest Accuracy: {accuracy_score(y_test, rf_pred):.4f}")
# 실제 값 vs 예측 값 비교
comparison_df = pd.DataFrame({
    '실제 값': y_test[:15].values,
    '예측 값': rf_pred[:15]
})
print("\n--- 실제 값 vs 예측 값 비교 (RandomForest) ---")
print(comparison_df)

Random Forest Accuracy: 0.8324

--- 실제 값 vs 예측 값 비교 (RandomForest) ---
    실제 값  예측 값
0      1     0
1      0     0
2      0     0
3      1     1
4      1     0
5      1     1
6      1     1
7      0     0
8      1     1
9      1     1
10     0     0
11     0     0
12     0     0
13     0     0
14     0     0

In [18]:
# 3. LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
print(f"Logistic Regression Accuracy: {accuracy_score(y_test, lr_pred):.4f}")
# 실제 값 vs 예측 값 비교
comparison_df = pd.DataFrame({
    '실제 값': y_test[:15].values,
    '예측 값': lr_pred[:15]
})
print("\n--- 실제 값 vs 예측 값 비교 (LogisticRegression) ---")
print(comparison_df)

Logistic Regression Accuracy: 0.8045

--- 실제 값 vs 예측 값 비교 (LogisticRegression) ---
    실제 값  예측 값
0      1     0
1      0     0
2      0     0
3      1     1
4      1     1
5      1     1
6      1     1
7      0     0
8      1     1
9      1     1
10     0     0
11     0     0
12     0     0
13     0     0
14     0     0

In [19]:
# 4. KNeighborsClassifier
knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
knn_pred = knn_model.predict(X_test)
print(f"KNN Accuracy: {accuracy_score(y_test, knn_pred):.4f}")
# 실제 값 vs 예측 값 비교
comparison_df = pd.DataFrame({
    '실제 값': y_test[:15].values,
    '예측 값': knn_pred[:15]
})
print("\n--- 실제 값 vs 예측 값 비교 (KNN) ---")
print(comparison_df)

KNN Accuracy: 0.8045

--- 실제 값 vs 예측 값 비교 (KNN) ---
    실제 값  예측 값
0      1     0
1      0     0
2      0     0
3      1     1
4      1     0
5      1     1
6      1     1
7      0     0
8      1     1
9      1     1
10     0     0
11     0     0
12     0     0
13     0     0
14     0     0